name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      staging_artifact_version:
        description: 'The version of the artifact from the staging deployment'
        required: true

jobs:
  promote_to_production:
    runs-on: [self-hosted, Linux, X64, nbt-runner]

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven


      # Use the same commit ID as the version for the production deployment
      - name: Deploy to Production
        run: |
          # Replace '/path/to/your/production/jar/target' with the path to your production JAR file on the VM
          echo "Workflow triggered by: ${{ github.actor }}"
          sshpass -p "${{ secrets.STAGE_SSH_PASSWORD }}" sudo scp -P 20202 adapters/*/*/target/${{ inputs.staging_artifact_version }} ${{ secrets.STAGE_SSH_USERNAME }}@${{ secrets.STAGE_VM_HOST }}:/opt/prod
